jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        # create users admin and dev
        - id: "admin"
          password: "admin"
        - id: "dev"
          password: "dev"
  authorizationStrategy: 
    globalMatrix:
      permissions:
        # assign permissions
        - "Job/Build:dev"
        - "Job/Cancel:dev"
        - "Job/Read:dev"
        - "Job/Workspace:dev"
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
          #        - "Run/Replay:dev"
          #        - "Run/Update:dev"
  # make sure our jenkins master has 1 executor so that we can run our pipelines
  numExecutors: 1
  
# specify the seedjob groovy script that will create the pipelines for us
jobs:
  - script: >
      multibranchPipelineJob('FlaskAppPipeline') {
        branchSources {
          git {
            id = 'FlaskApp'
            remote('http://giteadc:3000/dev/FlaskApp.git')
          }
        }

        triggers {
          cron("H/5 * * * *")
        }
      }
  - file: /usr/local/seedjob.groovy
